/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import modelo.Evento;

/**
 *
 * @author usuario
 */
public class InscribirEvent extends javax.swing.JFrame {

    private Evento e;
    private Menu menu;
    private int tUser;
    private ComplementoInscribirEvento regIns;

    public InscribirEvent(Menu menu) {
        this.menu = menu;
        getMenu().setVisible(false);
        initComponents();
        if (getMenu().getUsuario().getTipo().equals("Asociado")) {
            jLabel3.setVisible(false);
            jTextField3.setVisible(false);
            jTextField3.setText(getMenu().getUsuario().getId());
        }
        try {
            FillList();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscripcion Eventos");

        jLabel1.setText("Nombre Evento");

        jLabel2.setText("Codigo Evento");

        jLabel3.setText("Codigo Asociado");

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jButton2.setText("Consultar Evento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Registrar al Evento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Volver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(31, 31, 31)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultListModel<String> lista;
        String codigo, nombre;
        nombre = jTextField1.getText();
        codigo = jTextField2.getText();
        if (nombre == "") {
            nombre = null;
        }
        if (codigo == "") {
            codigo = null;
        }
        ArrayList<String> l = new ArrayList<String>();
        try {
            l = getMenu().getControlM().consultarEventoActivo(codigo, nombre);
            lista = new DefaultListModel<String>();
            for (String s : l) {
                lista.addElement(s);
            }
            jList1.setModel((lista));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String asociado = jTextField3.getText();
        if (asociado.equals("") || jList1.isSelectionEmpty()) {
            String message;
            if (asociado.equals("")) {
                message = "Ingrese el codigo del asociado.";
            } else {
                message = "Seleccione un evento.";
            }
            JOptionPane.showMessageDialog(null, "Error: " + message);

        } else {
            String s = jList1.getSelectedValue();
            String[] v = s.split(" - ");
            String codigo = v[0];
            try {
                e = getMenu().getControlA().ConsultarEventoDetalle(codigo);
                regIns = new ComplementoInscribirEvento(this, "Inscribir", asociado);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        getMenu().setVisible(true);
        getMenu().Close(this);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            if (jList1.isSelectionEmpty()) {
                throw new Exception("No hay un evento seleccionado.");
            } else {
                String s = jList1.getSelectedValue();
                String[] v = s.split(" - ");
                String codigo = v[0];

                e = getMenu().getControlA().ConsultarEventoDetalle(codigo);
                String cadena = "Codigo: " + e.getCodigo() + "\n"
                        + "Tipo Evento: " + e.getTipo() + "\n"
                        + "Nombre Evento: " + e.getNombre() + "\n"
                        + "Observacion: " + e.getObservacion() + "\n"
                        + "Lugar: " + e.getLugar() + "\n"
                        + "Fecha de Inicio: " + e.getfInicio() + "\n"
                        + "Fecha de Finalizacion: " + e.getfFin() + "\n"
                        + "Fecha Limite de Inscripcion: " + e.getfLimite() + "\n"
                        + "Cant Max Participantes: " + e.getCantParticipantes() + "\n"
                        + "Cant Participantes: " + e.getAsistentes() + "\n"
                        + "Valor Copago Unitario: " + e.getCopago() + "\n";
                if (getMenu().getUsuario().getTipo().equals("Funcionario")) {
                    cadena += "Proveedor: " + e.getProveedor().getNombre() + "\n"
                            + "Costo Total: " + String.valueOf(e.getCostoTotal()) + "\n"
                            + "% Subsidio: " + e.getPorcSubsidio() + "%\n"
                            + "ESTADO: " + e.getEstado() + "\n";
                }
                JOptionPane.showMessageDialog(null, cadena);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void FillList() throws Exception {
        DefaultListModel<String> lista;
        ArrayList<String> l = new ArrayList<String>();
        l = getMenu().getControlM().consultarEventosActivos();
        lista = new DefaultListModel<String>();
        for (String s : l) {
            lista.addElement(s);
        }
        jList1.setModel((lista));
    }

    public Menu getMenu() {
        return menu;
    }

    public Evento getEvento() {
        return e;
    }
}
